2017-11-19 14:17:04.126 [info] <0.33.0> Application lager started on node 'all_in_one_1@127.0.0.1'
2017-11-19 14:17:04.145 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@127.0.0.1'
2017-11-19 14:17:04.346 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@127.0.0.1'
2017-11-19 14:17:04.472 [error] <0.157.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.157.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:17:04.472 [error] <0.148.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:17:04.473 [error] <0.146.0> CRASH REPORT Process <0.146.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 14:17:04.473 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...}
2017-11-19 14:37:06.650 [error] <0.164.0> ** Connection attempt from disallowed node c286@localhost ** 
2017-11-19 14:37:49.725 [error] <0.166.0> ** Connection attempt from disallowed node c329@localhost ** 
2017-11-19 14:38:57.748 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:38:57.753 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:38:57.845 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:38:57.856 [error] <0.165.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.165.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:38:57.858 [error] <0.156.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:38:57.859 [error] <0.154.0> CRASH REPORT Process <0.154.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 14:38:57.859 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...}
2017-11-19 14:54:43.335 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:54:43.340 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:54:43.433 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:54:43.445 [error] <0.167.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.167.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:54:43.447 [error] <0.158.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:54:43.447 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 14:54:43.448 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...}
2017-11-19 14:55:58.347 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:55:58.352 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:55:58.447 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:55:58.459 [error] <0.167.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.167.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 14:55:58.461 [error] <0.158.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 14:55:58.461 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 14:55:58.461 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...}
2017-11-19 14:57:22.783 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:57:22.788 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-19 14:57:22.882 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-19 15:01:50.625 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-19 15:01:50.633 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-19 15:01:50.727 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-19 15:58:05.800 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-19 15:58:05.805 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-19 15:58:05.933 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-19 15:58:05.945 [error] <0.167.0>@net_server_sup:get_base_params:64 CRASH REPORT Process <0.167.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 64
2017-11-19 15:58:05.946 [error] <0.158.0>@net_server_sup:get_base_params:64 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 64 in context start_error
2017-11-19 15:58:05.947 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...} in application_master:init/4 line 134
2017-11-19 15:58:05.947 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"src/net_server/net_server_sup.erl"},{line,64}]},{net_server_sup,map_fun,1,[{file,"src/net_server/net_server_sup.erl"},{line,48}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{net_server_sup,init,1,[{file,"src/net_server/net_server_sup.erl"},{line,39}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,...},...]}}},...}
2017-11-19 16:07:35.411 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-19 16:07:35.416 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-19 16:07:35.532 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-19 16:07:35.555 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-19 16:09:35.717 [error] <0.169.0>@logic_server:loop CRASH REPORT Process <0.169.0> with 0 neighbours crashed with reason: call to undefined function logic_server:loop(#Port<0.3494>)
2017-11-19 18:38:26.611 [error] <0.170.0>@logic_server:loop CRASH REPORT Process <0.170.0> with 0 neighbours crashed with reason: call to undefined function logic_server:loop(#Port<0.3559>)
2017-11-20 01:13:30.894 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:13:30.899 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:13:31.001 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:13:31.015 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:30.698 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:30.703 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:30.787 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:30.801 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:37.238 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:37.243 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:37.319 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:18:37.333 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:25:33.479 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:25:33.484 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:25:33.576 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:25:33.590 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:27:43.728 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:27:43.733 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:27:43.832 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:27:43.846 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:29:16.591 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:29:16.596 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:29:16.683 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:29:16.697 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:30:27.003 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:30:27.008 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:30:27.084 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-20 01:30:27.098 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-22 21:29:53.064 [info] <0.33.0> Application lager started on node 'all_in_one_1@172.17.0.11'
2017-11-22 21:29:53.074 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@172.17.0.11'
2017-11-22 21:29:53.234 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@172.17.0.11'
2017-11-22 21:29:53.280 [info] <0.33.0> Application egame started on node 'all_in_one_1@172.17.0.11'
2017-11-22 21:47:53.839 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-22 21:47:53.846 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-22 21:48:08.012 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-22 21:48:08.037 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-22 22:08:50.714 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-22 22:08:50.721 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-22 22:09:04.888 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-22 22:09:04.919 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-22 22:21:59.461 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("debug logic_server get client ip error~n", [#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,...]) line 170 in lists:map/2 line 1239
2017-11-22 22:21:59.462 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["debug logic_server get client ip error~n",[#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,<<50,53,53,50,18,7,49,46,48,46,48,48,49>>,1]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,...}]},...]}}}
2017-11-22 22:21:59.488 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["debug logic_server get client ip error~n",[#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,<<50,53,53,50,18,7,49,46,48,46,48,48,49>>,1]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,...}]},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-22 22:21:59.488 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["debug logic_server get client ip error~n",[#Port<0.3809>,[49,50,45,49,50,52,53,50,50,51,52,8,1,16,0,24,233,7,34,20,10,9,49,50,52,53,50],1,<<50,53,53,50,18,7,49,46,48,46,48,48,49>>,1]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,...}]},...]}}} in context child_terminated
2017-11-24 01:49:50.383 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 01:49:50.398 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 01:50:04.611 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 01:50:04.685 [error] <0.161.0>@persistence:get_device_id_mapping CRASH REPORT Process <0.161.0> with 0 neighbours crashed with reason: call to undefined function persistence:get_device_id_mapping()
2017-11-24 01:50:04.685 [error] <0.153.0>@persistence:get_device_id_mapping Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason call to undefined function persistence:get_device_id_mapping() in context start_error
2017-11-24 01:50:04.685 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{undef,[{persistence,get_device_id_mapping,[],[]},{memcache,init_deviceid_index,1,[{file,"memcache.erl"},{line,133}]},{memcache,init,1,[{file,"memcache.erl"},{line,86}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-24 01:50:04.685 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,memcache,{undef,[{persistence,get_device_id_mapping,[],[]},{memcache,init_deviceid_index,1,[{file,"memcache.erl"},{line,133}]},{memcache,init,1,[{file,"memcache.erl"},{line,86}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}}
2017-11-24 02:11:18.450 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:11:18.471 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:11:32.699 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:11:32.746 [error] <0.161.0>@persistence:dets_foldl:74 CRASH REPORT Process <0.161.0> with 0 neighbours crashed with reason: bad argument in call to dets:first(user_dets) line 1266 in persistence:dets_foldl/3 line 74
2017-11-24 02:11:32.746 [error] <0.153.0>@persistence:dets_foldl:74 Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason bad argument in call to dets:first(user_dets) line 1266 in persistence:dets_foldl/3 line 74 in context start_error
2017-11-24 02:11:32.746 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{badarg,[{dets,first,[user_dets],[{file,"dets.erl"},{line,1266}]},{persistence,dets_foldl,3,[{file,"persistence.erl"},{line,74}]},{memcache,init_deviceid_ets,1,[{file,"memcache.erl"},{line,133}]},{memcache,init,1,[{file,"memcache.erl"},{line,86}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,...}} in application_master:init/4 line 134
2017-11-24 02:11:32.746 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,memcache,{badarg,[{dets,first,[user_dets],[{file,"dets.erl"},{line,1266}]},{persistence,dets_foldl,3,[{file,"persistence.erl"},{line,74}]},{memcache,init_deviceid_ets,1,[{file,"memcache.erl"},{line,133}]},{memcache,init,1,[{file,"memcache.erl"},{line,86}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,...}}
2017-11-24 02:13:32.003 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:13:32.008 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:13:46.161 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:13:46.186 [error] <0.160.0>@persistence:init CRASH REPORT Process <0.160.0> with 0 neighbours crashed with reason: call to undefined function persistence:init()
2017-11-24 02:13:46.186 [error] <0.153.0>@persistence:init Supervisor egame_sup had child init_base started with init_base:start_link() at undefined exit with reason call to undefined function persistence:init() in context start_error
2017-11-24 02:13:46.187 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_base,{undef,[{persistence,init,[],[]},{init_base,init,1,[{file,"init_base.erl"},{line,24}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-24 02:13:46.187 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,init_base,{undef,[{persistence,init,[],[]},{init_base,init,1,[{file,"init_base.erl"},{line,24}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}}
2017-11-24 02:16:35.071 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:16:35.077 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:16:49.225 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 02:16:49.251 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("persistence:init_dets ~w success ~p", [user_dets]) line 170 in lists:map/2 line 1239
2017-11-24 02:16:49.251 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["persistence:init_dets ~w success ~p",[user_dets]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,555}]},...]}}}
2017-11-24 02:16:49.260 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["persistence:init_dets ~w success ~p",[user_dets]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,555}]},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-24 02:16:49.260 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["persistence:init_dets ~w success ~p",[user_dets]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,4,[{file,"gen_event.erl"},{line,555}]},...]}}} in context child_terminated
2017-11-24 02:16:49.262 [error] <0.160.0>@user_db:init:23 CRASH REPORT Process <0.160.0> with 0 neighbours crashed with reason: bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23
2017-11-24 02:16:49.262 [error] <0.153.0>@user_db:init:23 Supervisor egame_sup had child init_base started with init_base:start_link() at undefined exit with reason bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23 in context start_error
2017-11-24 02:16:49.262 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_base,{badarg,[{ets,new,[user_ets,[set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]],[]},{user_db,init,0,[{file,"user_db.erl"},{line,23}]},{init_base,init,1,[{file,"init_base.erl"},{line,25}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,...}} in application_master:init/4 line 134
2017-11-24 02:16:49.263 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,init_base,{badarg,[{ets,new,[user_ets,[set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]],[]},{user_db,init,0,[{file,"user_db.erl"},{line,23}]},{init_base,init,1,[{file,"init_base.erl"},{line,25}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,...}}
2017-11-24 14:24:19.029 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:24:19.037 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:24:33.324 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:24:33.383 [error] <0.160.0>@user_db:init:23 CRASH REPORT Process <0.160.0> with 0 neighbours crashed with reason: bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23
2017-11-24 14:24:33.383 [error] <0.153.0>@user_db:init:23 Supervisor egame_sup had child init_base started with init_base:start_link() at undefined exit with reason bad argument in call to ets:new(user_ets, [set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]) in user_db:init/0 line 23 in context start_error
2017-11-24 14:24:33.384 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_base,{badarg,[{ets,new,[user_ets,[set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]],[]},{user_db,init,0,[{file,"user_db.erl"},{line,23}]},{init_base,init,1,[{file,"init_base.erl"},{line,25}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,...}} in application_master:init/4 line 134
2017-11-24 14:24:33.384 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,init_base,{badarg,[{ets,new,[user_ets,[set,named_table,public,compressed,{keypos,2},{heir,undefined,[]}]],[]},{user_db,init,0,[{file,"user_db.erl"},{line,23}]},{init_base,init,1,[{file,"init_base.erl"},{line,25}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,...}}
2017-11-24 14:26:30.996 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:26:31.003 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:26:45.255 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:26:45.354 [error] <0.165.0>@persistence:get_max_uid CRASH REPORT Process <0.165.0> with 0 neighbours crashed with reason: call to undefined function persistence:get_max_uid()
2017-11-24 14:26:45.354 [error] <0.153.0>@persistence:get_max_uid Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason call to undefined function persistence:get_max_uid() in context start_error
2017-11-24 14:26:45.355 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{undef,[{persistence,get_max_uid,[],[]},{memcache,init,1,[{file,"memcache.erl"},{line,87}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-24 14:26:45.355 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,memcache,{undef,[{persistence,get_max_uid,[],[]},{memcache,init,1,[{file,"memcache.erl"},{line,87}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}}
2017-11-24 14:28:39.407 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:28:39.422 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:28:53.629 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:28:53.719 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:52:57.458 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:52:57.466 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:53:11.734 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:53:11.815 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:53:28.497 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("logic_server:process_msg failed ~w ~p~n", [error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,...>>},...]) line 170 in lists:map/2 line 1239
2017-11-24 14:53:28.498 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["logic_server:process_msg failed ~w ~p~n",[error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,50,51,52,18,5,49,46,48,46,48>>},[{logic_server,process_msg,5,[{file,"logic_server.erl"},{line,61}]},{logic_server,loop,1,[{file,"logic_server.erl"},{line,41}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,...},...]}}}
2017-11-24 14:53:28.546 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["logic_server:process_msg failed ~w ~p~n",[error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,50,51,52,18,5,49,46,48,46,48>>},[{logic_server,process_msg,5,[{file,"logic_server.erl"},{line,61}]},{logic_server,loop,1,[{file,"logic_server.erl"},{line,41}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,...},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-24 14:53:28.546 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["logic_server:process_msg failed ~w ~p~n",[error,{badmatch,<<8,232,131,223,208,5,16,0,24,0,32,0,50,22,10,13,49,35,49,50,45,49,50,52,53,50,50,51,52,18,5,49,46,48,46,48>>},[{logic_server,process_msg,5,[{file,"logic_server.erl"},{line,61}]},{logic_server,loop,1,[{file,"logic_server.erl"},{line,41}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,...},...]}}} in context child_terminated
2017-11-24 14:54:55.919 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:54:55.926 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:55:10.102 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 14:55:10.153 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-24 15:03:15.805 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 15:03:15.810 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 15:03:29.951 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 15:03:29.983 [error] <0.166.0>@logic_servre:init CRASH REPORT Process <0.166.0> with 0 neighbours crashed with reason: call to undefined function logic_servre:init()
2017-11-24 15:03:29.983 [error] <0.153.0>@logic_servre:init Supervisor egame_sup had child init_sup started with init_sup:start_link() at undefined exit with reason call to undefined function logic_servre:init() in context start_error
2017-11-24 15:03:29.984 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,init_sup,{undef,[{logic_servre,init,[],[]},{init_sup,init,1,[{file,"init_sup.erl"},{line,29}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}} in application_master:init/4 line 134
2017-11-24 15:03:29.984 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,init_sup,{undef,[{logic_servre,init,[],[]},{init_sup,init,1,[{file,"init_sup.erl"},{line,29}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{egame_app,start,[normal,[]]}}
2017-11-24 17:16:01.420 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 17:16:01.428 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 17:16:15.589 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 17:16:15.642 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-24 19:08:58.764 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-24 19:08:58.769 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-24 19:09:12.961 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-24 19:09:13.029 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:13:53.009 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:13:53.020 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:14:07.266 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:14:07.342 [error] <0.165.0>@persistence:-get_device_id_dict/0-fun-0-:53 CRASH REPORT Process <0.165.0> with 0 neighbours crashed with reason: no match of right hand value [{user,2,"12-12452234",undefined,16777218,1511523611,undefined,1511523611,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[]}] in persistence:'-get_device_id_dict/0-fun-0-'/3 line 53
2017-11-29 17:14:07.342 [error] <0.153.0>@persistence:-get_device_id_dict/0-fun-0-:53 Supervisor egame_sup had child memcache started with memcache:start_link() at undefined exit with reason no match of right hand value [{user,2,"12-12452234",undefined,16777218,1511523611,undefined,1511523611,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[]}] in persistence:'-get_device_id_dict/0-fun-0-'/3 line 53 in context start_error
2017-11-29 17:14:07.342 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,memcache,{{badmatch,[{user,2,"12-12452234",undefined,16777218,1511523611,undefined,1511523611,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[]}]},[{persistence,'-get_device_id_dict/0-fun-0-',3,[{file,"persistence.erl"},{line,53}]},{persistence,dets_foldl_0,4,[{file,"persistence.erl"},{line,78}]},{memcache,init_deviceid_ets,1,[{file,"memcache.erl"},{line,140}]},{memcache,...},...]}}},...} in application_master:init/4 line 134
2017-11-29 17:14:07.343 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,memcache,{{badmatch,[{user,2,"12-12452234",undefined,16777218,1511523611,undefined,1511523611,undefined,{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[]}]},[{persistence,'-get_device_id_dict/0-fun-0-',3,[{file,"persistence.erl"},{line,53}]},{persistence,dets_foldl_0,4,[{file,"persistence.erl"},{line,78}]},{memcache,init_deviceid_ets,1,[{file,"memcache.erl"},{line,140}]},{memcache,...},...]}}},...}
2017-11-29 17:15:45.533 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:15:45.539 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:15:59.710 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:15:59.754 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:36:35.105 [error] <0.38.0> Loading of /home/lifan/egame/server/ebin/tcp_server.beam failed: not_purged
2017-11-29 17:36:42.430 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:36:42.437 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:36:56.603 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:36:56.645 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:38:37.506 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:38:37.514 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:38:51.696 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-29 17:38:51.735 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-29 18:51:36.384 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-29 18:51:36.389 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-29 18:51:50.568 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-29 18:51:50.621 [error] <0.169.0>@net_server_sup:get_base_params:66 CRASH REPORT Process <0.169.0> with 0 neighbours crashed with reason: no match of right hand value undefined in net_server_sup:get_base_params/3 line 66
2017-11-29 18:51:50.621 [error] <0.153.0>@net_server_sup:get_base_params:66 Supervisor egame_sup had child net_server_sup started with net_server_sup:start_link() at undefined exit with reason no match of right hand value undefined in net_server_sup:get_base_params/3 line 66 in context start_error
2017-11-29 18:51:50.627 [error] <0.151.0> CRASH REPORT Process <0.151.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"net_server/net_server_sup.erl"},{line,66}]},{net_server_sup,map_fun,1,[{file,"net_server/net_server_sup.erl"},{line,50}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{net_server_sup,init,1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{supervisor,...},...]}}},...} in application_master:init/4 line 134
2017-11-29 18:51:50.627 [info] <0.33.0> Application egame exited with reason: {{shutdown,{failed_to_start_child,net_server_sup,{{badmatch,undefined},[{net_server_sup,get_base_params,3,[{file,"net_server/net_server_sup.erl"},{line,66}]},{net_server_sup,map_fun,1,[{file,"net_server/net_server_sup.erl"},{line,50}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{net_server_sup,'-init/1-lc$^0/1-0-',1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{net_server_sup,init,1,[{file,"net_server/net_server_sup.erl"},{line,41}]},{supervisor,...},...]}}},...}
2017-11-29 18:59:10.627 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-29 18:59:10.633 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-29 18:59:24.812 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-29 18:59:24.876 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-29 19:15:12.761 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-29 19:15:12.768 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-29 19:15:26.923 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-29 19:15:26.987 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-30 18:39:56.963 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-30 18:39:56.971 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-30 18:40:11.176 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-30 18:40:11.267 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-30 20:47:18.236 [info] <0.33.0> Application lager started on node 'all_in_one_1@192.168.191.128'
2017-11-30 20:47:18.243 [info] <0.33.0> Application log4erl started on node 'all_in_one_1@192.168.191.128'
2017-11-30 20:47:32.420 [info] <0.33.0> Application mnesia started on node 'all_in_one_1@192.168.191.128'
2017-11-30 20:47:32.467 [info] <0.33.0> Application egame started on node 'all_in_one_1@192.168.191.128'
2017-11-30 20:57:15.447 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("down msg is ~p~n", {down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}) line 170 in lists:map/2 line 1239
2017-11-30 20:57:15.447 [error] <0.156.0> gen_server <0.156.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}}
2017-11-30 20:57:15.506 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-30 20:57:15.507 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.156.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in context child_terminated
2017-11-30 21:00:03.927 [error] <0.103.0>@lists:map:1239 gen_event {file_appender,app2} installed in default_logger terminated with reason: bad argument in call to io_lib:format("down msg is ~p~n", {down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}) line 170 in lists:map/2 line 1239
2017-11-30 21:00:03.928 [error] <0.11754.0> gen_server <0.11754.0> terminated with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}}
2017-11-30 21:00:03.928 [error] <0.11754.0> CRASH REPORT Process <0.11754.0> with 0 neighbours exited with reason: {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in gen_server:handle_common_reply/8 line 726
2017-11-30 21:00:03.928 [error] <0.102.0> Supervisor log4erl_sup had child app2 started with logger_guard:start_link(default_logger, file_appender, app2, {conf,[{dir,"./logs"},{level,info},{file,dgame},{type,size},{max,10240000},{suffix,log},{rotation,...},...]}) at <0.11754.0> exit with reason {appender_died,{'EXIT',{badarg,[{io_lib,format,["down msg is ~p~n",{down_msg,undefined,undefined,undefined,undefined,undefined,undefined,undefined}],[{file,"io_lib.erl"},{line,170}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{lists,map,2,[{file,"lists.erl"},{line,1239}]},{file_appender,do_log,2,[{file,"src/file_appender.erl"},{line,118}]},{file_appender,handle_event,2,[{file,"src/file_appender.erl"},{line,82}]},{gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},{gen_event,server_notify,...},...]}}} in context child_terminated
